# Generated by Django 4.2 on 2023-04-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gender_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Job_type",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("salary", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Employed_register",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=50)),
                ("born", models.DateField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("register_time", models.DateTimeField()),
                ("photo", models.ImageField(upload_to="")),
                (
                    "employed_function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.job_type"
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.gender"
                    ),
                ),
            ],
        ),
    ]
